### ISSUE TITLE
Could not get class storage for 

### ISSUE THREAD

**Issue by AidynMakhataev** [psalm/laravel-psalm-plugin#107]
**Describe the bug**
After updating to 1.4.0 version, psalm was crashed by following error

```
░░░░░░[2020-08-21 19:05:05] development.ERROR: Could not get class storage for 
Stack trace in the forked worker:
#0 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php(340): Psalm\Internal\Provider\ClassLikeStorageProvider->get()
#1 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(173): Psalm\Internal\Analyzer\Statements\Expression\Call\Method\AtomicMethodCallAnalyzer::analyze()
#2 /myproject/vendor/psalm/plugin-laravel/src/ReturnTypeProvider/ModelReturnTypeProvider.php(86): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze()
#3 /myproject/vendor/psalm/plugin-laravel/src/ReturnTypeProvider/ModelReturnTypeProvider.php(49): Psalm\LaravelPlugin\ReturnTypeProvider\ModelReturnTypeProvider::executeFakeCall()
#4 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Provider/MethodReturnTypeProvider.php(108): Psalm\LaravelPlugin\ReturnTypeProvider\ModelReturnTypeProvider::getMethodReturnType()
#5 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(985): Psalm\Internal\Provider\MethodReturnTypeProvider->getReturnType()
#6 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(154): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze()
#7 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#8 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(50): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#9 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(150): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze()
#10 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#11 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/AssignmentAnalyzer.php(164): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#12 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(131): Psalm\Internal\Analyzer\Statements\Expression\AssignmentAnalyzer::analyze()
#13 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression()
#14 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(500): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze()
#15 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement()
#16 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(570): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze()
#17 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1921): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze()
#18 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(748): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod()
#19 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(221): Psalm\Internal\Analyzer\ClassAnalyzer->analyze()
#20 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(349): Psalm\Internal\Analyzer\FileAnalyzer->analyze()
#21 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(184): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}()
#22 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(415): Psalm\Internal\Fork\Pool->__construct()
#23 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(275): Psalm\Internal\Codebase\Analyzer->doAnalysis()
#24 /myproject/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(632): Psalm\Internal\Codebase\Analyzer->analyzeFiles()
#25 /myproject/vendor/vimeo/psalm/src/psalm.php(680): Psalm\Internal\Analyzer\ProjectAnalyzer->check()
#26 /myproject/vendor/vimeo/psalm/psalm(2): require_once('/home/user/mypr...')
#27 {main}

  at vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:348
    344|                             if ($this->task_done_closure !== null) {
    345|                                 ($this->task_done_closure)($message->data);
    346|                             }
    347|                         } elseif ($message instanceof ForkProcessErrorMessage) {
  > 348|                             throw new \Exception($message->message);
    349|                         } else {
    350|                             error_log('Child should return ForkMessage - response type=' . gettype($message));
    351|                             $this->did_have_error = true;
    352|                         }


```

**Impacted Versions**

`barryvdh/laravel-ide-helper               v2.8.0`
`laravel/framework                         v7.25.0`
`vimeo/psalm                               3.14.1`
`psalm/plugin-laravel                      v1.4.0`

**Comment by Gummibeer** [comment]
For me this error still exists. I'm in `vimeo/psalm:3.14.2` and `psalm/plugin-laravel:1.4.0`.

My `psalm.xml` is:
```xml
<?xml version="1.0"?>
<psalm
    xmlns="https://getpsalm.org/schema/config"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    errorLevel="6"
    resolveFromConfigFile="true"
>
    <projectFiles>
        <directory name="app"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <plugins>
        <pluginClass class="Psalm\LaravelPlugin\Plugin"/>
    </plugins>
</psalm>
```

And the full error output is:
```
❯ vendor/bin/psalm
Scanning files...
Analyzing files...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
   Exception 

  Could not get class storage for eloquent
Stack trace in the forked worker:
#0 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/StaticCallAnalyzer.php(94): Psalm\Internal\Provider\ClassLikeStorageProvider->get('Eloquent')
#1 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(154): Psalm\Internal\Analyzer\Statements\Expression\Call\StaticCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#2 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context), false, NULL, false)
#3 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/MethodCallAnalyzer.php(50): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\StaticCall), Object(Psalm\Context))
#4 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(150): Psalm\Internal\Analyzer\Statements\Expression\Call\MethodCallAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#5 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ExpressionAnalyzer.php(45): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::handleExpression(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context), false, NULL, false)
#6 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/ReturnAnalyzer.php(138): Psalm\Internal\Analyzer\Statements\ExpressionAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Expr\MethodCall), Object(Psalm\Context))
#7 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(474): Psalm\Internal\Analyzer\Statements\ReturnAnalyzer::analyze(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context))
#8 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/StatementsAnalyzer.php(169): Psalm\Internal\Analyzer\StatementsAnalyzer::analyzeStatement(Object(Psalm\Internal\Analyzer\StatementsAnalyzer), Object(PhpParser\Node\Stmt\Return_), Object(Psalm\Context), Object(Psalm\Context))
#9 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php(570): Psalm\Internal\Analyzer\StatementsAnalyzer->analyze(Array, Object(Psalm\Context), Object(Psalm\Context), true)
#10 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(1921): Psalm\Internal\Analyzer\FunctionLikeAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Internal\Provider\NodeDataProvider), Object(Psalm\Context))
#11 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(748): Psalm\Internal\Analyzer\ClassAnalyzer->analyzeClassMethod(Object(PhpParser\Node\Stmt\ClassMethod), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Context), Object(Psalm\Context))
#12 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(221): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#13 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(349): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#14 vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php(193): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(4, '...')
#15 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(415): Psalm\Internal\Fork\Pool->__construct(Array, Object(Closure), Object(Closure), Object(Closure), Object(Closure))
#16 vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(275): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 11)
#17 vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(648): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 11, false, true)
#18 vendor/vimeo/psalm/src/psalm.php(680): Psalm\Internal\Analyzer\ProjectAnalyzer->check('...', false)
#19 vendor/vimeo/psalm/psalm(2): require_once('...')
#20 {main}

  at vendor/vimeo/psalm/src/Psalm/Internal/Fork/Pool.php:357
    353|                             if ($this->task_done_closure !== null) {
    354|                                 ($this->task_done_closure)($message->data);
    355|                             }
    356|                         } elseif ($message instanceof ForkProcessErrorMessage) {
  > 357|                             throw new \Exception($message->message);
    358|                         } else {
    359|                             error_log('Child should return ForkMessage - response type=' . gettype($message));
    360|                             $this->did_have_error = true;
    361|                         }
```

**Comment by Gummibeer** [comment]
After playing around a bit it seems like the `public function newQuery(): Builder` method on my `User` model is the problem.
Possibly because @barryvdh laravel-ide-helper always generates the `@method static Builder|User newQuery()` line independent if it's already defined in the class or not.
As soon as I move the method into my base model or fully remove it everything is fine and psalm runs again.
